glory_category:
    path:     /admin/category
    defaults: { _controller: GloryCategoryBundle:Admin:index }

glory_category_create:
    path:     /admin/category/create
    defaults: { _controller: GloryCategoryBundle:Admin:create }

glory_category_show:
    path:     /admin/category/{id}
    defaults: { _controller: GloryCategoryBundle:Admin:show }

glory_category_add:
    path:     /admin/category/{id}/add
    defaults: { _controller: GloryCategoryBundle:Admin:add }

glory_category_edit:
    path:     /admin/category/{id}/edit
    defaults: { _controller: GloryCategoryBundle:Admin:edit }

glory_category_delete:
    path:     /admin/category/{id}/delete
    defaults: { _controller: GloryCategoryBundle:Admin:delete }
