services:
    glory_category.category_manager:
        class: Glory\Bundle\CategoryBundle\Model\CategoryManager
        arguments: [@service_container]
        
    glory_category.form.category:
        class: Glory\Bundle\CategoryBundle\Form\Type\CategoryFormType
        arguments: [@glory_category.category_manager]
        tags: 
            - { name: form.type, alias: glory_category_form }
    glory_category.form.category_type:
        class: Glory\Bundle\CategoryBundle\Form\Type\CategoryTypeFormType
        arguments: [@glory_category.category_manager]
        tags: 
            - { name: form.type, alias: glory_category_type_form }
    
    glory_category.form.category_type:
        class: Glory\Bundle\CategoryBundle\Form\Type\CategoryType
        tags: 
            - { name: form.type, alias: category }

    glory_category.event.weight_listener:
        class: Glory\Bundle\CategoryBundle\EventListener\CategoryWeightListener
        tags:
            -  { name: doctrine.event_subscriber }
